name: dask-cluster
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
    - pandas==2.2.3
    - numpy==2.1
    - dask[complete]==2024.9.1
    - s3fs==2024.9.0
    - dask-expr==1.1.15
    - awscli
    - jupyter
    - boto3  
