apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-scheduler
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      containers:
      - name: dask-scheduler
        image: longtong/dask-cluster-image #daskdev/dask:latest
        args: ["dask-scheduler"]
        ports:
        - containerPort: 8786
        - containerPort: 8787
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
spec:
  type: NodePort
  selector:
    app: dask-scheduler
  ports:
  - name: scheduler
    port: 8786
    targetPort: 8786
    nodePort: 31876  # Within 30000-65535 range
  - name: dashboard
    port: 8787
    targetPort: 8787
    nodePort: 31877  # Within 30000-65535 range
